### ISSUE TITLE
crosslink-uploader-app & interactionviewer-app etc

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/psi-jami#15]
Hi @colin-combe, 

do you know anything about crosslink-uploader-app, interactionviewer-app, jami-crosslink-csv or jami-html ?

Thanks

**Comment by colin-combe** [comment]
Yes, they are tomcat servlets written by Marine that convert cross-link 
data in CSV format to PSI-MI XML (crosslink uploader app) and a servlet 
that converts PSI-MI XML to our MI-JSON format.

For me, they are sort of useful. They also serve as examples of how to 
use JAMI.

c

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
Thanks Colin! Would you mind to add a little readme.md to these packages? Just explaining briefly what they do.

**Comment by colin-combe** [comment]
OK, I'll close this issue when there's a pull request for the readme's
c

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
This relates to issue #16

**Comment by colin-combe** [comment]
we've removed these modules
