### ISSUE TITLE
Crosslink packages

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/psi-jami#16]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [crosslink-uploader-app](https://github.com/MICommunity/psi-jami/tree/master/crosslink-uploader-app)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [interactionviewer-app](https://github.com/MICommunity/psi-jami/tree/master/interactionviewer-app)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-crosslink-csv](https://github.com/MICommunity/psi-jami/tree/master/jami-crosslink-csv)
    - [x] README.md
    - [x] Test coverage  (No test coverage, see issue #38)
    - [x] Java example
- [jami-html](https://github.com/MICommunity/psi-jami/tree/master/jami-html)
    - [x] README.md
    - [x] Test coverage (No test coverage, see issue #31)
    - [x] Java example

**Comment by tschaka1904** [comment]
Are interactionviewer-app and crosslink-uploader-app rightly placed in JAMI? Maybe move them outside?

**Comment by colin-combe** [comment]
> Are interactionviewer-app and crosslink-uploader-app rightly placed in JAMI?

For me it is convenient to have them there, it means they are build with the rest of JAMi and have their dependencies sorted it.

> Maybe move them outside?

If you want. (Though I'd prefer not to.) 

jami-cross-link-csv & jami-html definitely do belong in JAMI. jami-html is not cross-link specific.

**Comment by colin-combe** [comment]
> Are interactionviewer-app and crosslink-uploader-app rightly placed in JAMI?

@tschaka1904 Actually Max, on reflection you're right about this. They don't belong there, we should take them out.

I will make a "JAMI servlets" project containing them (in my account) and they can be removed from psi-jami whenever.

**Comment by colin-combe** [comment]
They are here: https://github.com/colin-combe/jami-servlets
This can be forked into the mi-community account if others wish, but I think I was the only one who made use of them.
interactionviewer-app and crosslink-uploader-app can be removed from psi-jami.
