### ISSUE TITLE
jami-core

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/psi-jami#17]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )

https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami

- [analysis/graph](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/analysis/graph)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example
- [binary](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/binary)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example
- [datasource](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/datasource)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [exception](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/exception)
    - [x] README.md
    - [x] Test coverage
    - [x] ~Java example~
- [factory](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/factory)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example
- [listener](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/listener)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example
- [model](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/model)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example
- [utils](https://github.com/MICommunity/psi-jami/tree/master/jami-core/src/main/java/psidev/psi/mi/jami/utils)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example

**Comment by tschaka1904** [comment]
What are `psi-jami/jami-core/src/main/resources/interactorDatabase.properties & interactorType.properties` used for? We need description where and for what it is used.

**Comment by tschaka1904** [comment]
Is the a need for the `psi-jami/jami-core/src/main/assembly/descriptor.xml` for?

**Comment by tschaka1904** [comment]
Should we use a lib for checksum instead of `psi-jami/jami-core/src/main/java/psidev/psi/mi/jami/utils/checksum`?

**Comment by tschaka1904** [comment]
`jami-core/datasource` provides interfaces for of sources and stream to receive interaction data.

**Comment by julie-sullivan** [comment]
@tschaka1904 That `/assembly/description.xml` file is a mistake and should be removed. I confirmed this with @danielabutano. Maven has assembly.xml but not description.xml. Why would you need to create a custom zip file anyway?

**Comment by julie-sullivan** [comment]
Interaction and InteractionEvidence is in the model package. BinaryInteraction and BinaryInteractionEvidence is in the `/binary` directory. Why?

**Comment by julie-sullivan** [comment]
Also, the word `binary` means something in computer science. Having `binary` directory is confusing! This should be renamed.

**Comment by julie-sullivan** [comment]
`jami-core/analysis/graph` is used to calculate cliques, which is used to calculate inferred interactions. This is used when writing interaction XML. 

What are inferred interactions used for?

**Comment by julie-sullivan** [comment]
`jami-core/binary', in addition to having a bunch of classes that should be in the model, also handles the expansion.

**Comment by tschaka1904** [comment]
Should we refactor utils or do we want to keep it?

**Comment by julie-sullivan** [comment]
![image](https://cloud.githubusercontent.com/assets/1663057/17513342/540aaffa-5e24-11e6-89a2-6f535c546ff4.png)

**Comment by tschaka1904** [comment]
We should move the wrapper classes out of `psidev.psi.mi.jami.binary.impl`. Maybe into utils?

**Comment by julie-sullivan** [comment]
![image](https://cloud.githubusercontent.com/assets/1663057/17513387/9be144ec-5e24-11e6-9f68-ee298471fc0d.png)


binary package is tested well.

**Comment by julie-sullivan** [comment]
![image](https://cloud.githubusercontent.com/assets/1663057/17513420/cc71e4c2-5e24-11e6-936a-0d37f317e2e7.png)

Overall test coverage is okay for psi-core

**Comment by julie-sullivan** [comment]
`jami-core/datasource' has no tests, but that's okay. It's just a bunch of interfaces. Same for `jami-core/exceptions`

**Comment by tschaka1904** [comment]
**About inferred interactions** Sandra said:

>I think this was the terminology we used for cases such as the curated complexes, or also when we were attempting to add cases where a binding site was created by the binding of 2 molecules then a third protein bound into it.

**Comment by julie-sullivan** [comment]
Could not run either test in `psi-core/factory`

```
Aug 09, 2016 11:58:48 AM psidev.psi.mi.jami.factory.MIDataSourceFactory getMIDataSourceWith
WARNING: We cannot instantiate data source of type class psidev.psi.mi.jami.datasource.MockExperimentDataSource with the given options.
java.lang.IllegalArgumentException: no source option
	at psidev.psi.mi.jami.datasource.MockExperimentDataSource.initialiseContext(MockExperimentDataSource.java:20)
	at psidev.psi.mi.jami.factory.MIDataSourceFactory.instantiateNewDataSource(MIDataSourceFactory.java:156)
	at psidev.psi.mi.jami.factory.MIDataSourceFactory.getMIDataSourceWith(MIDataSourceFactory.java:55)
	at psidev.psi.mi.jami.factory.MiDataSourceFactoryTest.test_missing_file_data_source_options(MiDataSourceFactoryTest.java:35)
```

**Comment by tschaka1904** [comment]
<img width="551" alt="screen shot 2016-08-09 at 12 11 30" src="https://cloud.githubusercontent.com/assets/5269116/17514482/c66d296e-5e2a-11e6-9a9b-ce068a24cddd.png">
test coverage of model package

**Comment by tschaka1904** [comment]
<img width="554" alt="screen shot 2016-08-09 at 12 19 45" src="https://cloud.githubusercontent.com/assets/5269116/17514639/a91427e0-5e2b-11e6-954e-af37934bd743.png">

test coverage of factory package

**Comment by tschaka1904** [comment]
<img width="550" alt="screen shot 2016-08-09 at 12 21 37" src="https://cloud.githubusercontent.com/assets/5269116/17514692/e9080e48-5e2b-11e6-9707-b6253c3345c1.png">
test coverage of listener package. There are no test's

**Comment by tschaka1904** [comment]
<img width="557" alt="screen shot 2016-08-09 at 12 22 58" src="https://cloud.githubusercontent.com/assets/5269116/17514730/1898d278-5e2c-11e6-830f-218fe9de9cab.png">

test coverage of utils package.

**Comment by julie-sullivan** [comment]
Datasource is a bad name for this package. (Maybe because a data source is a specific thing in InterMine!). 

I would prefer "stream helper" or stream handler. Something that indicates what this package actually does. Even better than documentation!
