### ISSUE TITLE
jami-commons

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#19]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [/jami-commons](https://github.com/MICommunity/psi-jami/tree/master/jami-commons)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by julie-sullivan** [comment]
Why is this different from jami-core?

**Comment by yochannah** [comment]
Test coverage: ![image](https://cloud.githubusercontent.com/assets/9271438/17512625/ab4bd130-5e20-11e6-8cf0-2ac7bf4c8e44.png)

**Comment by yochannah** [comment]
https://github.com/MICommunity/psi-jami/blob/28a336ea0bf59f1b9aef8fb176ad84f32bc08d3c/jami-commons/README.md
