### ISSUE TITLE
jami-imex-updater

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#20]
intact specific, so lower priority

[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [jami-imex-updater](https://github.com/MICommunity/psi-jami/tree/master/jami-imex-updater)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by git4anjali** [comment]
Test Coverage :- 

![jami-imex-update](https://cloud.githubusercontent.com/assets/16086137/17550578/8777df74-5eed-11e6-90cd-85f16731e613.png)
