### ISSUE TITLE
jami-interactionviewer-json

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#21]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [jami-interactionviewer-json](https://github.com/MICommunity/psi-jami/tree/master/jami-interactionviewer-json)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by julie-sullivan** [comment]
Package is only used to write JSON for the interaction viewer (I assume?). Good ticket for @colin-combe and @joshkh

**Comment by joshkh** [comment]
![image](https://cloud.githubusercontent.com/assets/4752532/17481160/718c23e4-5d73-11e6-9c4d-f7715f83215e.png)
