### ISSUE TITLE
jami-bridges

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#23]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )

https://github.com/MICommunity/psi-jami/tree/master/jami-bridges

- [bridges-core](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/bridges-core)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-chebi](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-chebi)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-europubmedcentral](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-europubmedcentral)
    - [x] README.md
    - [x] Test coverage
    - [ ] Java example
- [jami-imexcentral](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-imexcentral)
    - [x] README.md - incomplete (no code example)
    - [x] Test coverage
    - [ ] Java example
- [ 	jami-obo](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-obo)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-ols](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-ols)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-ontology-manager](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-ontology-manager)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-picr](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-picr)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-uniprot-taxonomy](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-uniprot-taxonomy)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-uniprot](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-uniprot)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [jami-unisave](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/jami-unisave)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example
- [uniprot-mapping](https://github.com/MICommunity/psi-jami/tree/master/jami-bridges/uniprot-mapping)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by julie-sullivan** [comment]
There are no tests for this package at all that I can see.

Might be good as this would alert us if a web service provider changes their API (which has happened!).

**Comment by julie-sullivan** [comment]
Test coverage

- jami-chebi - no test

**Comment by julie-sullivan** [comment]
Are all of these bridges used?

**Comment by yochannah** [comment]
uniprot-mapping test coverage: ![image](https://cloud.githubusercontent.com/assets/9271438/17514252/77cc3fda-5e29-11e6-9b01-b37937d67330.png)

**Comment by yochannah** [comment]
jami-uniprot test coverage:
![image](https://cloud.githubusercontent.com/assets/9271438/17517048/884e9b72-5e39-11e6-9041-7321486648db.png)

**Comment by julie-sullivan** [comment]
See #36
