### ISSUE TITLE
jami-mitab

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#24]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [jami-mitab](https://github.com/MICommunity/psi-jami/tree/master/jami-mitab)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by diegoalonso78** [comment]
Test coverage for jami-mitab

![coverage report](https://cloud.githubusercontent.com/assets/12297444/17550350/d831c1a8-5ef4-11e6-9a54-6ae883983a6c.jpg)

The top line doesn't make sense (we couldn't run test coverage only within the package), so below you can see actual data.

![coverage ii](https://cloud.githubusercontent.com/assets/12297444/17550444/4f4909e0-5ef5-11e6-9974-9eeaf2783a04.jpg)
