### ISSUE TITLE
jami-xml

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#25]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [jami-xml](https://github.com/MICommunity/psi-jami/tree/master/jami-xml)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by noedelta** [comment]
It has some schema documentation for 3.0, maybe would be a good idea to have one for 2.5 too. https://github.com/MICommunity/psi-jami/tree/master/jami-xml/documentation/schema

**Comment by noedelta** [comment]
Test coverage for jami-xml
![image](https://cloud.githubusercontent.com/assets/7516607/17513121/14ed94d2-5e23-11e6-8da2-b43bc69b5af5.png)

Some tests are marked as `@Ignore`. The reasons behind need further investigation.
