### ISSUE TITLE
jami-enricher

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/psi-jami#26]
[General workshop guidance ](https://docs.google.com/document/d/1CQ1rOyU-d7hQSQmOXi9IbunILvzA5T6ehHXLXCGzHmc/edit?usp=sharing )
- [jami-enricher](https://github.com/MICommunity/psi-jami/tree/master/jami-enricher)
    - [x] README.md
    - [x] Test coverage
    - [x] Java example

**Comment by danielabutano** [comment]
Test Coverage
![image](https://cloud.githubusercontent.com/assets/1678179/17513629/fae60b7a-5e25-11e6-9bd4-4bd130792548.png)
