### ISSUE TITLE
Accept attributes enclosed in single quotes

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/psi-jami#46]
Josh noticed this at the hackathon, foolishly, we omitted to make issue for it at time...

Full url of problem file is ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psi30/datasets/Archaea/10449718.xml 

The reader is configured as in the ReadWriteJsonWithJAMI.java example (despite its name this example does not read json, it reads xml or mitab, #41). That is, as follows:

`       // the option factory for reading files and other datasources
        MIDataSourceOptionFactory optionfactory = MIDataSourceOptionFactory.getInstance();
        // the datasource factory for reading MITAB/PSI-MI XML files and other datasources
        MIDataSourceFactory dataSourceFactory = MIDataSourceFactory.getInstance();

        // get default options for a file. It will identify if the file is MITAB or PSI-MI XML file and then it will load the appropriate options.
        // By default, the datasource will be streaming (only returns an iterator of interactions), and returns a source of Interaction objects.
        // The default options can be overridden using the optionfactory or by manually adding options listed in MitabDataSourceOptions or PsiXmlDataSourceOptions
        Map<String, Object> parsingOptions = optionfactory.getDefaultOptions(new File(fileName));

        InteractionStream interactionSource = null;
        InteractionWriter jsonInteractionWriter = null;
        try{
            // Get the stream of interactions knowing the default options for this file
            interactionSource = dataSourceFactory.
                    getInteractionSourceWith(parsingOptions);`

The error I get is as follows:
`Jan 09, 2017 1:52:53 PM psidev.psi.mi.jami.xml.cache.PsiXmlFileIndexCache buildPositionIndex
INFO: length = 20726
Exception in thread "main" psidev.psi.mi.jami.exception.MIIOException: Impossible to read next interaction.
	at psidev.psi.mi.jami.xml.io.iterator.AbstractXmlIterator.processNextBinary(AbstractXmlIterator.java:53)
	at psidev.psi.mi.jami.xml.io.iterator.AbstractXmlIterator.<init>(AbstractXmlIterator.java:31)
	at psidev.psi.mi.jami.xml.io.iterator.XmlInteractionEvidenceIterator.<init>(XmlInteractionEvidenceIterator.java:17)
	at psidev.psi.mi.jami.xml.model.extension.datasource.XmlEvidenceStreamSource.createXmlIterator(XmlEvidenceStreamSource.java:84)
	at psidev.psi.mi.jami.xml.model.extension.datasource.AbstractPsiXmlStream.getInteractionsIterator(AbstractPsiXmlStream.java:108)
	at psidev.psi.mi.jami.xml.model.extension.datasource.DefaultPsiXmlStreamSource.getInteractionsIterator(DefaultPsiXmlStreamSource.java:44)
	at psidev.psi.mi.jami.examples.interactionviewer.ReadWriteJsonWithJami.main(ReadWriteJsonWithJami.java:79)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at psidev.psi.mi.jami.xml.cache.PsiXmlFileIndexCache.buildPositionIndex(PsiXmlFileIndexCache.java:815)
	at psidev.psi.mi.jami.xml.cache.PsiXmlFileIndexCache.<init>(PsiXmlFileIndexCache.java:127)
	at psidev.psi.mi.jami.xml.io.parser.AbstractPsiXmlParser.initialiseDefaultCache(AbstractPsiXmlParser.java:1010)
	at psidev.psi.mi.jami.xml.io.parser.AbstractPsiXmlParser.initialiseEntryContext(AbstractPsiXmlParser.java:1001)
	at psidev.psi.mi.jami.xml.io.parser.AbstractPsiXmlParser.parseNextInteraction(AbstractPsiXmlParser.java:164)
	at psidev.psi.mi.jami.xml.io.iterator.AbstractXmlIterator.processNextBinary(AbstractXmlIterator.java:39)
	... 6 more`

**Comment by git4anjali** [comment]
I looked into this a little bit and found that said ReadWriteJsonWithJAMI.java supports xml 2.5 and not 3.0 and probably thus the problem.

**Comment by colin-combe** [comment]
How did you determine this? I see some of the comments in the code refer to "iterator for parsing xml 2.5 interactions" but I thought we were good with reading XML v.3.0.

It reads other xml v3.0 files I have tried it with - is this just chance?
 
It should use our standard PSI-MI XML parser or automatically recognise type of file and behave accordingly? (I could be mistaken about how things work.) I don't see anything else in other examples for specifically reading XML v3.0?

if we can't read v3.0 XML its a problem for us, right? Maybe we should ask Marine about this...

**Comment by colin-combe** [comment]
Its the very first line of the file.
If you change:
<?xml version='1.0' encoding='UTF-8'?>
to:
<?xml version="1.0" encoding="UTF-8"?>
then it works.

Seems like the parser doesn't like the double quotes. Its something around [lines 811 -  816 of PsiXmlFileIndexCache. ](https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/cache/PsiXmlFileIndexCache.java#L811-L816)

Its not going to be too hard to fix...

**Comment by colin-combe** [comment]
I renamed this issue (is that bad practice?) to 'Accept attributes enclosed in single quotes' as I think there is a general problem with this in the XML parser. XML with attributes in single quotes is [valid](https://www.w3.org/TR/xml/#NT-AttValue).

The problem is present in the following places:
- https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/cache/PsiXmlFileIndexCache.java#L811-L816
- https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/cache/PsiXmlFileIndexCache.java#L46
- https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/io/parser/AbstractFullPsiXmlParser.java#L375-L377

I would fix it but I'm having trouble working with develop branch.

**Comment by colin-combe** [comment]
Um, I'm perplexed... I cannot replicate this error now. I can't explain why.

For me,  ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psi30/datasets/Archaea/10449718.xml works fine now, regardless of quote type used. (Incidentally, it seems like the type of quote mark on the first line is determined by the browser you use to download it.)

Does anyone know of anything that's changed that might explain this? Does it work for other people? (Josh, maybe you could test it again since you first spotted the problem.)

I don't think this issue is _all through_ the XML parser. My reading of the code is that it only affects the line 1 xml declaration and the attributes of the top level entrySet element, which gives the schema version. But in practice it seems to not cause any problem at all.

Does it default to version 3.0 now if it can't read these attributes?

It others don't have a prob with that file then maybe we can just close this and pretend it never happened...

**Comment by colin-combe** [comment]
Its doing it again now (failing if first line uses single quotes)

**Comment by colin-combe** [comment]
Ah... I understand.

The code at 
https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/cache/PsiXmlFileIndexCache.java#L811-L816 
does have an error, I think, whereby it is hardcoded into it that the _encoding_ attribute is surrounded in double quotes.

However, if you look closely at the code then whether it crashes or not will depend on the quoting of the **preceding** attribute. To go through all combinations:

`<xml version="1.0" encoding="UTF-8"?>`
works as you would expect, sets encoding to `UTF-8.`

<xml version='1.0' encoding="UTF-8"?>
again, works as you would expect and sets encoding to `UTF-8`

<xml version='1.0' encoding='UTF-8'?>
fails as you would expect, specifically it ends up calling `truncatedLine.substring(0, -1);` which is an exception because endIndex < beginIndex and it crashes.

(here comes the tricky one)
<xml version="1.0" encoding='UTF-8'?>
If you follow through the code, you will see that this will set the 'encoding' to 'on=', which is gibberish, but it avoids the crash and then carries on as normal.

phew. Glad I saw what was happening there. (No, I haven't been looking at this all day... I had a meeting in the middle.)

I'll have a look at fixing.

**Comment by colin-combe** [comment]
I added another commit (365ab2a450a069180d93070962f80b1e483e8a91) to my develop branch (it will appear in pull request #51) which changes the regular expression used to get Ids (er... which IDs I'm not absolutely sure).

Without this, the  getId method (https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/cache/PsiXmlFileIndexCache.java#L942-#L965) was always returning -1 when the file used single quotes. However, it didn't seem to do any harm.

All tests still pass.

I've looked at 
https://github.com/MICommunity/psi-jami/blob/master/jami-xml/src/main/java/psidev/psi/mi/jami/xml/io/parser/AbstractFullPsiXmlParser.java#L375-L377
and the situation is a bit more complicated; "fixing" it breaks things. I'll give it another go later in the week or provide more info on whats happening here.

**Comment by colin-combe** [comment]
I think all these quote mark issues are resolved now.

pull #51 should fix

All tests still pass. 

Also, I did a search and replace on all the files in /test/resources/samples (and subfolder thereof) replacing `"` with `'` , then reran the tests. They all passed again. That search and replace change isn't committed and my pull request doesn't change the test files.

I think the initial problem spotted by Josh was because he used chrome to download the XML file and it puts single quote marks in XML declaration.

I think this can be closed and, once checked by others, merged into develop.
