### ISSUE TITLE
problems working on the develop branch?

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/psi-jami#47]
I was looking at fixing issue #46, and wanted to make the changes against the develop branch (as we are supposed to).

However, I find I can't work with the develop branch because I can't get it to compile.

E.g. when I try to build just the xml module it fails saying: 
`Could not find artifact psidev.psi.mi.jami:jami-core:jar:3.0.6-SNAPSHOT in nexus-ebi-repo-old (http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/)`

Any advice on how to work with it?

Also, looking at the network graph, is there a minor issue with changes/workarounds made to the master branch but not the develop branch?

cheers,
c

**Comment by tschaka1904** [comment]
> E.g. when I try to build just the xml module it fails saying:
Could not find artifact psidev.psi.mi.jami:jami-core:jar:3.0.6-SNAPSHOT in nexus-ebi-repo-old (http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/)

Please run: `mvn install -Dmaven.test.skip=true`, this should install `psidev.psi.mi.jami:jami-core:jar:3.0.6-SNAPSHOT` in your local maven repository.

**Comment by colin-combe** [comment]
Thanks Max. You're right. I don't know how to work maven.

also, no need to skip tests as core in develop branch is passing them
