### ISSUE TITLE
One version for JAMI

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/psi-jami#5]
I was releasing PSI-JAMI the other day and it was quite painful to deal with all of its sub-modules. This is because they do all have different version number, whilst the 'master'-pom is just in version 1.0.1. Maybe we can find a way to unify the version. Anyone a reasonable suggestion?

**Comment by colin-combe** [comment]
On 07/03/16 13:55, Maximilian Koch wrote:
> Anyone a reasonable suggestion?

Do away with version numbers on sub-modules?


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
Sorry how do you mean that?

**Comment by colin-combe** [comment]
I was was proposing we just remove version numbers from the sub-modules 
and only keep the top level version number. Maybe that's not possible, I 
don't know...

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tschaka1904** [comment]
Yes this would be the cleanest approach, but I have also no idea what to do. I'm sure it will cause some trouble, because JAMI is already used and people might directly to jami-uniprot-1.1.2.
