### ISSUE TITLE
jami-ontology-index

### ISSUE THREAD

**Issue by tschaka1904** [MICommunity/psi-jami#6]
Hi all, 

I was cleaning up PSI-JAMI today in the development branch to prepare for version 3.0. I have found a module, which is not used and doesn't use PSI-JAMI as it's parent. The module is called: jami-ontology-index

Does anyone know about it? Should we do with it? 

Cheers,
Max

**Comment by tschaka1904** [comment]
I was just confirming that it wasn't me disabling it on some point in the past. It was already disabled, as Marine was working on it: https://github.com/MICommunity/PSI-JAMI/blob/3c283fa3dc94de143b815695ff50decd290c3491/pom.xml

**Comment by julie-sullivan** [comment]
Duplicate of #22
